// Semua command aksi/roleplay (hug, lick, kill, punch, dll).
// `source` nentuin API mana yang dipanggil buat ambil GIF-nya:
//   - 'nekos'  -> https://nekos.best/api/v2/<category>
//   - 'waifu'  -> https://api.waifu.pics/sfw/<category>
// (dua-duanya gratis, tidak butuh API key, aman buat konten SFW/anime)
const ACTIONS = {
	hug: {
		emoji: '🤗',
		label: 'Hug',
		verb: 'meluk',
		source: 'nekos',
		category: 'hug',
		color: 0xff6fae,
		aliases: ['phug'],
	},
	kiss: {
		emoji: '😘',
		label: 'Kiss',
		verb: 'cium',
		source: 'nekos',
		category: 'kiss',
		color: 0xff85c2,
		aliases: ['pkiss'],
	},
	pat: {
		emoji: '🤚',
		label: 'Pat',
		verb: 'elus kepala',
		source: 'nekos',
		category: 'pat',
		color: 0xffd97a,
		aliases: ['ppat'],
	},
	cuddle: {
		emoji: '🥰',
		label: 'Cuddle',
		verb: 'peluk manja',
		source: 'nekos',
		category: 'cuddle',
		color: 0xffb3d9,
		aliases: ['pcuddle'],
	},
	slap: {
		emoji: '✋',
		label: 'Slap',
		verb: 'tampar',
		source: 'nekos',
		category: 'slap',
		color: 0xed4245,
		aliases: ['pslap'],
	},
	punch: {
		emoji: '👊',
		label: 'Punch',
		verb: 'tinju',
		source: 'nekos',
		category: 'punch',
		color: 0xed4245,
		aliases: ['ppunch'],
	},
	kick: {
		emoji: '🦵',
		label: 'Kick',
		verb: 'tendang',
		source: 'nekos',
		category: 'kick',
		color: 0xed4245,
		aliases: ['pkick'],
	},
	bite: {
		emoji: '😬',
		label: 'Bite',
		verb: 'gigit',
		source: 'nekos',
		category: 'bite',
		color: 0xf47b02,
		aliases: ['pbite'],
	},
	poke: {
		emoji: '👉',
		label: 'Poke',
		verb: 'sodok',
		source: 'nekos',
		category: 'poke',
		color: 0x5865f2,
		aliases: ['ppoke'],
	},
	tickle: {
		emoji: '🤣',
		label: 'Tickle',
		verb: 'gelitikin',
		source: 'nekos',
		category: 'tickle',
		color: 0xfee75c,
		aliases: ['ptickle'],
	},
	highfive: {
		emoji: '🙌',
		label: 'High Five',
		verb: 'tos sama',
		source: 'nekos',
		category: 'highfive',
		color: 0x57f287,
		aliases: ['phighfive', 'ptos'],
	},
	wave: {
		emoji: '👋',
		label: 'Wave',
		verb: 'lambai ke',
		source: 'nekos',
		category: 'wave',
		color: 0x5865f2,
		aliases: ['pwave'],
	},
	wink: {
		emoji: '😉',
		label: 'Wink',
		verb: 'kedipin mata ke',
		source: 'nekos',
		category: 'wink',
		color: 0x5865f2,
		aliases: ['pwink'],
	},
	lick: {
		emoji: '👅',
		label: 'Lick',
		verb: 'jilat',
		source: 'waifu',
		category: 'lick',
		color: 0xf47b02,
		aliases: ['plick'],
	},
	kill: {
		emoji: '🔪',
		label: 'Kill',
		verb: "'habisin' (bercanda doang 😆)",
		source: 'waifu',
		category: 'kill',
		color: 0x2b2d31,
		aliases: ['pkill'],
	},
	bonk: {
		emoji: '🔨',
		label: 'Bonk',
		verb: 'bonk kepala',
		source: 'waifu',
		category: 'bonk',
		color: 0xed4245,
		aliases: ['pbonk'],
	},
	yeet: {
		emoji: '🚀',
		label: 'Yeet',
		verb: 'yeet (lempar jauh-jauh)',
		source: 'nekos',
		category: 'yeet',
		color: 0xf47b02,
		aliases: ['pyeet'],
	},
	smug: {
		emoji: '😏',
		label: 'Smug',
		verb: 'pasang muka smug ke',
		source: 'nekos',
		category: 'smug',
		color: 0x5865f2,
		aliases: ['psmug'],
	},
};

module.exports = { ACTIONS };
